-- Trip Checklist: waiver signing + document uploads (private storage).
--
-- These tables are the source of truth for the Trip Checklist. They are
-- RLS-locked with NO policies: only the Node API (service role) reads/writes
-- them. The browser never touches them directly. Document files live in a
-- PRIVATE storage bucket; admins view them via short-lived signed URLs minted
-- server-side. (Legacy user_verifications / licenses bucket are left intact.)

CREATE TABLE IF NOT EXISTS public.booking_waivers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  typed_name text NOT NULL,
  agreed_terms boolean NOT NULL,
  agreed_safety boolean NOT NULL,
  signed_at timestamptz DEFAULT now(),
  ip_address text
);

CREATE INDEX IF NOT EXISTS idx_booking_waivers_booking_id ON public.booking_waivers (booking_id);

CREATE TABLE IF NOT EXISTS public.booking_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  document_type text NOT NULL,
  storage_path text NOT NULL,
  status text DEFAULT 'uploaded',
  rejection_note text,
  uploaded_at timestamptz DEFAULT now(),
  approved_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_booking_documents_booking_id ON public.booking_documents (booking_id);

DO $$ BEGIN
  ALTER TABLE public.booking_documents
    ADD CONSTRAINT booking_documents_document_type_check
    CHECK (document_type IN ('buoy_insurance_proof', 'government_id', 'boater_safety_card'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.booking_documents
    ADD CONSTRAINT booking_documents_status_check
    CHECK (status IN ('uploaded', 'approved', 'rejected'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.booking_waivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_documents ENABLE ROW LEVEL SECURITY;
-- No policies on purpose: anon/authenticated are denied; the service-role API
-- bypasses RLS for every read/write.

-- Private document bucket: not publicly readable. Files are reached only through
-- signed URLs generated by the service role for admin review.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'trip-documents',
  'trip-documents',
  false,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf']::text[]
)
ON CONFLICT (id) DO NOTHING;
